### ISSUE TITLE
menu problem

### ISSUE THREAD

**Issue by phildobbin** [mbadran/headlights#15]
Hi.

Headlights works fine in MacVim but I've no menus set in vim & when I start vim I get pages of errors. Debug mode shows this:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/users/dobbin/.vim/bundle/Headlights/plugin/headlights.py", line 55, in __init__
    self.attach_menus()
  File "/users/dobbin/.vim/bundle/Headlights/plugin/headlights.py", line 585, in attach_menus
    self.do_debug()
  File "/users/dobbin/.vim/bundle/Headlights/plugin/headlights.py", line 606, in do_debug
    log_file = tempfile.NamedTemporaryFile(prefix=LOGNAME_PREFIX, suffix=LOGNAME_SUFFIX, delete=False)
TypeError: NamedTemporaryFile() got an unexpected keyword argument 'delete'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/users/dobbin/.vim/bundle/Headlights/plugin/headlights.py", line 55, in __init__
    self.attach_menus()
  File "/users/dobbin/.vim/bundle/Headlights/plugin/headlights.py", line 585, in attach_menus
    self.do_debug()
  File "/users/dobbin/.vim/bundle/Headlights/plugin/headlights.py", line 606, in do_debug
    log_file = tempfile.NamedTemporaryFile(prefix=LOGNAME_PREFIX, suffix=LOGNAME_SUFFIX, delete=False)
TypeError: NamedTemporaryFile() got an unexpected keyword argument 'delete'`

Any help appreciated...

**Comment by mbadran** [comment]
Which version of Python are you running? It sounds like an issue with your Python interpeter.

In Vim, run these two commands in sequence:

:python import sys
:python print sys.version

**Comment by mbadran** [comment]
Also, which version of vim are you running in the terminal? Can you paste the output of the :version command? Thanks.

**Comment by phildobbin** [comment]
On 18/1/12 22:17, "Mohammed"
<reply+i-2731452-ba6bf24a67544f261e66765ff51c37514b301409-1141800@reply.gith
ub.com> wrote:

> Which version of Python are you running? It sounds like an issue with your
> Python interpeter.
> 
> In Vim, run these two commands in sequence:
> 
> :python import sys
> :python print sys.version

Hi.

Interestingly Vim reports Python as being v. 2.5.6:88840 whereas `python
--version` from the cli returns 2.7.2 which is what I expected (I'm using a
port installed version of Python from Mac Ports for py27).

My version of Vim is 7.3-353 on OS X. I didn't try installing on my Debian
boxes because they're at Vim 7.2.

Cheers,

```
Phil...
```

## 

Some [people] feel that the best way to improve Perl would be to go
back in time and shoot the author before he wrote it.
                                                       -Larry Wall

**Comment by phildobbin** [comment]
On 18/1/12 22:28, "Mohammed"
<reply+i-2731452-ba6bf24a67544f261e66765ff51c37514b301409-1141800@reply.gith
ub.com> wrote:

> Also, which version of vim are you running in the terminal? Can you paste the
> output of the :version command? Thanks.

# 

$ vim --version
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Dec 14 2011 10:35:32)
MacOS X (unix) version
Included patches: 1-244, 246-353
Compiled by dobbin@darkstar.local
Normal version without GUI.  Features included (+) or not (-):
-arabic +autocmd -balloon_eval -browse +builtin_terms +byte_offset +cindent
-clientserver +clipboard +cmdline_compl +cmdline_hist +cmdline_info
+comments 
-conceal +cryptv -cscope +cursorbind +cursorshape +dialog_con +diff
+digraphs 
-dnd -ebcdic -emacs_tags +eval +ex_extra +extra_search -farsi +file_in_path
+find_in_path +float +folding -footer +fork() +gettext -hangul_input +iconv
+insert_expand +jumplist -keymap -langmap +libcall +linebreak +lispindent
+listcmds +localmap -lua +menu +mksession +modify_fname +mouse -mouseshape
-mouse_dec -mouse_gpm -mouse_jsbterm -mouse_netterm -mouse_sysmouse
+mouse_xterm -mouse_urxvt +multi_byte +multi_lang -mzscheme +netbeans_intg
+path_extra +perl +persistent_undo +postscript +printer -profile +python
-python3 +quickfix +reltime -rightleft +ruby +scrollbind +signs +smartindent
-sniff +startuptime +statusline -sun_workshop +syntax +tag_binary
+tag_old_static -tag_any_white +tcl +terminfo +termresponse +textobjects
+title
 -toolbar +user_commands +vertsplit +virtualedit +visual +visualextra
+viminfo 
+vreplace +wildignore +wildmenu +windows +writebackup -X11 -xfontset -xim
-xsmp
 -xterm_clipboard -xterm_save
   system vimrc file: "/opt/local/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
      user exrc file: "$HOME/.exrc"
  fall-back for $VIM: "/opt/local/share/vim"
Compilation: /usr/bin/gcc-4.2 -c -I. -Iproto -DHAVE_CONFIG_H
-I/opt/local/include -DMACOS_X_UNIX -no-cpp-precomp  -pipe -O2 -arch x86_64
-D_FORTIFY_SOURCE=1     -I/opt/local/include  -D_DARWIN_C_SOURCE=1
Linking: /usr/bin/gcc-4.2   -L. -L/opt/local/lib      -L/opt/local/lib -arch
x86_64 -L/usr/local/lib -o vim       -lncurses -liconv -lintl -framework
Cocoa    -L/opt/local/lib  -fstack-protector
-L/opt/local/lib/perl5/5.12.3/darwin-multi-2level/CORE -lperl -lm -lutil -lc
-L/opt/local/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/
config -lpython2.5 -u _PyMac_Error
/opt/local/Library/Frameworks/Python.framework/Versions/2.5/Python
-L/opt/local/lib -ltcl8.5 -lruby -lobjc  -L/opt/local/lib

# 

Cheers,

```
Phil...
```

**Comment by mbadran** [comment]
Thanks for the info. Headlights requires Python 2.6+, so this is a compatibility issue. Maybe the MacPorts version was compiled incorrectly? See if you can find a more recent version, maybe via Homebrew (http://mxcl.github.com/homebrew/).

Note to self: I had a Python version check in the plugin script, but I took it out to speed up performance. Maybe I should put it back in again.

**Comment by phildobbin** [comment]
On 18/1/12 22:57, "Mohammed"
<reply+i-2731452-ba6bf24a67544f261e66765ff51c37514b301409-1141800@reply.gith
ub.com> wrote:

> Thanks for the info. Headlights requires Python 2.6+, so this is a
> compatibility issue. Maybe the MacPorts version was compiled incorrectly? See
> if you can find a more recent version, maybe via Homebrew
> (http://mxcl.github.com/homebrew/).
> 
> Note to self: I had a Python version check in the plugin script, but I took it
> out to speed up performance. Maybe I should put it back in again.

I've actually got py25, 26, 27 & 32 & Vim itself was compiled with py26 so
I'm puzzled as to why Vim is using the Apple supplied System Python (I know
it's using the rvm supplied Ruby that I compiled it with because the
Command-T plugin doesn't work because of it).

As for homebrew, it's not a good idea to run it concurrently with Mac Ports
& also I've got several things I compiled myself in /usr/local & it wanted
me to trash them.

My $PATH contains py27 as seen from the --version command so I'm not sure
how to proceed.

Cheers,

```
Phil...
```

## 

Some [people] feel that the best way to improve Perl would be to go
back in time and shoot the author before he wrote it.
                                                       -Larry Wall

**Comment by phildobbin** [comment]
On 18/1/12 22:57, "Mohammed"
<reply+i-2731452-ba6bf24a67544f261e66765ff51c37514b301409-1141800@reply.gith
ub.com> wrote:

> Thanks for the info. Headlights requires Python 2.6+, so this is a
> compatibility issue. Maybe the MacPorts version was compiled incorrectly? See
> if you can find a more recent version, maybe via Homebrew
> (http://mxcl.github.com/homebrew/).

Scrub that last message. I've just read the Vim version output properly this
time & Vim was compiled with py25. My bad.

Sorry for the noise,

Cheers,

```
Phil...
```

## 

Some [people] feel that the best way to improve Perl would be to go
back in time and shoot the author before he wrote it.
                                                       -Larry Wall

**Comment by mbadran** [comment]
No worries.

Hopefully you'll find a version of MacPorts with python2.6 or higher.
