### ISSUE TITLE
Error with Headlights

### ISSUE THREAD

**Issue by ssbanerje** [mbadran/headlights#24]
I am using headlights with MacVim 7.4 and Pathogen. I dont know what is going wrong, inside vim i get an error message saying that an error occurred and points me to a error log which contains...

```
Headlights -- Vim Debug Log

DATE: Mon Jun  9 16:16:55 2014
PLATFORM: Darwin-13.2.0-x86_64-i386-64bit

This is the debug log for Headlights <https://github.com/mbadran/headlights/>
For details on how to raise a GitHub issue, see :help headlights-issues
Don't forget to disable debug mode if you've specifically enabled it.

ERRORS:
Traceback (most recent call last):
  File "/Users/subho/.vim/bundle/headlights/plugin/headlights.py", line 29, in run_headlights
    parse_categories()
  File "/Users/subho/.vim/bundle/headlights/plugin/headlights.py", line 123, in parse_categories
    function(hl_categories[key].strip().split("\n"))
  File "/Users/subho/.vim/bundle/headlights/plugin/headlights.py", line 330, in parse_functions
    source_script["functions"].append(function)
TypeError: 'NoneType' object has no attribute '__getitem__'

parse_mappings: source script not initialised for mapping 'v  <BS>          "-d'
parse_mappings: lhs not found for mapping ''

SCRIPTNAMES:
1: /usr/local/Cellar/macvim/7.4-73/MacVim.app/Contents/Resources/vim/vimrc
  2: ~/.vimrc
  3: /usr/local/Cellar/macvim/7.4-73/MacVim.app/Contents/Resources/vim/runtime/syntax/syntax.vim
  4: /usr/local/Cellar/macvim/7.4-73/MacVim.app/Contents/Resources/vim/runtime/syntax/synload.vim
  5: /usr/local/Cellar/macvim/7.4-73/MacVim.app/Contents/Resources/vim/runtime/syntax/syncolor.vim
  6: /usr/local/Cellar/macvim/7.4-73/MacVim.app/Contents/Resources/vim/runtime/filetype.vim
  7: /usr/local/Cellar/macvim/7.4-73/MacVim.app/Contents/Resources/vim/runtime/menu.vim
  8: /usr/local/Cellar/macvim/7.4-73/MacVim.app/Contents/Resources/vim/runtime/autoload/paste.vim
  9: ~/.vim/autoload/pathogen.vim
 10: /usr/local/Cellar/macvim/7.4-73/MacVim.app/Contents/Resources/vim/runtime/ftoff.vim
 11: ~/.vim/bundle/vim-git/ftdetect/git.vim
....
....
....
function <SNR>39_StartExplorer(curBufNum)
    Last set from ~/.vim/bundle/minibufexpl.vim/plugin/minibufexpl.vim
function syntastic#util#decodeXMLEntities(string)
    Last set from ~/.vim/bundle/syntastic/autoload/syntastic/util.vim
function nerdtree#closeTree()
    Last set from ~/.vim/bundle/nerdtree/autoload/nerdtree.vim
function <SNR>33_PositionCursor(placement, flag_visual_mode, pos1, pos2)
    Last set from ~/.vim/bundle/cvim/autoload/mmtemplates/core.vim
function xolox#notes#foldexpr()
    Last set from ~/.vim/bundle/vim-notes/autoload/xolox/notes.vim

MENUS:
amenu <silent> 9997.300 Bundles.-SepHLD- :
amenu <silent> 9997.310 Bundles.debug.Open\ Log<Tab>/var/folders/pb/x0fb74y15y50bxlq3rccy7km0000gn/T/headlights_2BtiPz\.log :tabnew /var/folders/pb/x0fb74y15y50bxlq3rccy7km0000gn/T/headlights_2BtiPz.log<CR>
amenu <silent> 9997.320 Bundles.debug.Explore\ in\ Vim<Tab>/var/folders/pb/x0fb74y15y50bxlq3rccy7km0000gn/T :Texplore /var/folders/pb/x0fb74y15y50bxlq3rccy7km0000gn/T<CR>
amenu <silent> 9997.330 Bundles.debug.Explore\ in\ System<Tab>/var/folders/pb/x0fb74y15y50bxlq3rccy7km0000gn/T :!open /var/folders/pb/x0fb74y15y50bxlq3rccy7km0000gn/T<CR>

Headlights vim code executed in 0.01 seconds
Headlights python code executed in 0.06 seconds

(Vim menu commands not timed.)
```

What could the problem be? How do I fix it?

**Comment by rompe** [comment]
It looks like one of your bundles doesn't define any function. Try binary searching for that bundle by disabling one half of the extensions (except this one, of course), then the other half, and when you know in which half the problematic bundle resides, investigate these part in halves, until you found the one that doesn't play well with headlights. Report the bundle here.
The original author of headlights doesn't seem to be active anymore, but reporting back may motivate others (like me) to fix the bug.

**Comment by gambledor** [comment]
Headlights -- Vim Debug Log

DATE: Wed Jul 15 10:23:59 2015
PLATFORM: Darwin-13.4.0-x86_64-i386-64bit

This is the debug log for Headlights https://github.com/mbadran/headlights/
For details on how to raise a GitHub issue, see :help headlights-issues
Don't forget to disable debug mode if you've specifically enabled it.

ERRORS:
Traceback (most recent call last):
  File "~/vimrc/bundle/headlights/plugin/headlights.py", line 30, in run_headlights
    gen_menus()
  File "~/vimrc/bundle/headlights/plugin/headlights.py", line 139, in gen_menus
    gen_menu_categories(name, prefix, path, properties)
  File "~/vimrc/bundle/headlights/plugin/headlights.py", line 416, in gen_menu_categories
    gen_mappings_menu(properties["mappings"], prefix)
  File "~/vimrc/bundle/headlights/plugin/headlights.py", line 496, in gen_mappings_menu
    mode = sanitise_menu(mode)
  File "~/vimrc/bundle/headlights/plugin/headlights.py", line 380, in sanitise_menu
    return menu.replace("\", "\\").replace("|", "\|").replace(".", "\.").replace(" ", "\ ").replace("<", "\<")
AttributeError: 'NoneType' object has no attribute 'replace'

parse_mappings: source script not initialised for mapping 'x  <BS>          "-d'
parse_mappings: lhs not found for mapping ''
