### ISSUE TITLE
error executing HeadlightsTurnOn

### ISSUE THREAD

**Issue by jmatraszek** [mbadran/headlights#9]
When i try to execute HeadlightsTurnOn I get following message:
"Error detected while processing function <SNR>35_MakeMenu:
line 47:
Headlights exception: list index out of range"

**Comment by mbadran** [comment]
Thanks for reporting this!

So I can troubleshoot, can you please enable "g:headlights_debug"?

Put this value in your .vimrc:

let g:headlights_debug = 1

Then, after Vim loads, run the :messages command to see the location of the debug file. It would help if I saw the contents of that file (email to mebadran AT gmail or upload to a paste site).

Disable debugging when done. Thanks again.

**Comment by jmatraszek** [comment]
messages shows only "messages mantainer: Barm Moolenaar Bram@vim.org". But when i execute :HeadlightTurnOn I get "Headlights exception: global name 'LOGNAME_PREFIX' is not defined".

**Comment by mbadran** [comment]
Thanks. I'll investigate and release a new version soon.

**Comment by valpackett** [comment]
I have this:
    Error detected while processing function <SNR>24_MakeMenu:
    line   47:
    Headlights exception: local variable 'mode' referenced before assignment

**Comment by mbadran** [comment]
Hi guys,

I've improved the debug feature so it should now be working OK.

Can you please download the latest plugin files (headlights.vim and headlights.py), enable debug mode, and try again? Be sure to remove the 'execute "HeadlightsTurnOn"' command from your .vimrc.

This time, you should get the full exception trace when you run the Vim :messages command, and a detailed debug log will be generated for me to examine.

Thanks for your help troubleshooting this!

**Comment by mbadran** [comment]
The latest release (v1.2) has much more robust error handling. I expect that these errors will no longer occur, but I can't confirm that without seeing your debug log or replicating your setup.

Please download the latest release and give it another shot. I'll leave this issue open for a while in case you want to follow up.

Thanks for using Headlights :)

**Comment by Taverius** [comment]
I hope this is the right place? Seems related:

```
Error detected while processing function <SNR>18_RequestVimMenus:
Line 11:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Taverius\.vim\bundle\Headlights\plugin\headlights.py", line 55, in __init__
    self.attach_menus()
  File "C:\Users\Taverius\.vim\bundle\Headlights\plugin\headlights.py", line 556, in attach_menus
    DEBUG_MSG = "See the '%(root)s > debug' menu for details.%(sep)c" % locals()
TypeError: %c requires int or char
```

Vim 7.3.244 (self-compiled, WinSDK 7.1), Python 2.7.1.4 (ActiveState), Vundle, Headlights 1.2 straight off VimScript.

I don't have a lot of python stuff for vim, but it all seems to run fine ...

You do say Python 2.6+ ...

**Comment by mbadran** [comment]
Thank you for reporting this, Taverius. It seems like it's a cross platform issue with line separators, but there may be additional problems. I think I can reproduce this, stay tuned for a fix soon.

**Comment by mbadran** [comment]
So the good news is that I've fixed the line separator issue (trivial). Headlights should work fine now. You can download the latest source archive for the fix.

The bad news is that Headlights does not look pretty on Windows. At all. I developed this on MacVim, and there are a few UI (menu) glitches that slipped through.

I'm going to spend some time cleaning it up, and release a new version soon (not so trivial). This also applies to Linux.
